# Specify default build target.
[build]
target = "x86_64-rux.json"

# Use `build-std` feature to compile `core` for our target.
[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
